CREATE TABLE  `mod_tdmcreate_modules` (
  `mod_id` int(5) unsigned NOT NULL auto_increment,
  `mod_name` varchar(255) NOT NULL default '',
  `mod_version` varchar(5) NOT NULL default '',
  `mod_since` varchar(5) NOT NULL default '',
  `mod_min_php` varchar (5) NOT NULL default '',
  `mod_min_xoops` varchar (5) NOT NULL default '',
  `mod_min_admin` varchar (5) NOT NULL default '',
  `mod_min_mysql` varchar (5) NOT NULL default '',
  `mod_description` text,
  `mod_author` varchar(255) NOT NULL default '',
  `mod_author_mail` varchar(255) NOT NULL default '',
  `mod_author_website_url` varchar(255) NOT NULL default '',
  `mod_author_website_name` varchar(255) NOT NULL default '',
  `mod_credits` varchar(255) NOT NULL default '',
  `mod_license` varchar(255) NOT NULL default '',
  `mod_release_info` varchar(255) NOT NULL default '',
  `mod_release_file` varchar(255) NOT NULL default '',
  `mod_manual` varchar(255) NOT NULL default '',
  `mod_manual_file` varchar(255) NOT NULL default '',
  `mod_image` varchar(255) NOT NULL default '',
  `mod_demo_site_url` varchar(255) NOT NULL default '',
  `mod_demo_site_name` varchar(255) NOT NULL default '',
  `mod_support_url` varchar(255) NOT NULL default '',
  `mod_support_name` varchar(255) NOT NULL default '',
  `mod_website_url` varchar(255) NOT NULL default '',
  `mod_website_name` varchar(255) NOT NULL default '',
  `mod_release` varchar(11) NOT NULL default '00-00-0000',
  `mod_status` varchar(150) NOT NULL default '',
  `mod_admin` tinyint(1) unsigned NOT NULL default '1',
  `mod_user` tinyint(1) unsigned NOT NULL default '1',
  `mod_search` tinyint(1) unsigned NOT NULL default '0',
  `mod_comments` tinyint(1) unsigned NOT NULL default '0',
  `mod_notifications` tinyint(1) unsigned NOT NULL default '0',
  `mod_permissions` tinyint(1) unsigned NOT NULL default '0',
  `mod_install` tinyint(1) unsigned NOT NULL default '0',
  `mod_donations` varchar(50) NOT NULL default '',
  `mod_subversion` varchar(10) NOT NULL default '',
  PRIMARY KEY (`mod_id`)
) ENGINE=MyISAM;


CREATE TABLE  `mod_tdmcreate_tables` (
  `table_id` int(5) unsigned NOT NULL  auto_increment,
  `table_mid` int(5) unsigned NOT NULL default '0',
  `table_category` tinyint(1) unsigned NOT NULL default '0',
  `table_name` varchar(150) NOT NULL default '',
  `table_fieldname` varchar(150) NOT NULL default '',
  `table_image` varchar(150) NOT NULL default '',
  `table_nbfields` int(5) unsigned NOT NULL default '0',
  `table_fields` text,
  `table_parameters` text,
  `table_blocks` tinyint(1) unsigned NOT NULL default '0',
  `table_admin` tinyint(1) unsigned NOT NULL default '1',
  `table_user` tinyint(1) unsigned NOT NULL default '0',
  `table_status` tinyint(1) unsigned NOT NULL default '0',
  `table_waiting` tinyint(1) unsigned NOT NULL default '0',
  `table_online` tinyint(1) unsigned NOT NULL default '0',
  `table_search` tinyint(1) unsigned NOT NULL default '0',
  `table_comments` tinyint(1) unsigned NOT NULL default '0',
  `table_notifications` tinyint(1) unsigned NOT NULL default '0',
  `table_permissions` tinyint(1) unsigned NOT NULL default '0',
  PRIMARY KEY (`table_id`)
) ENGINE=MyISAM;